### ISSUE TITLE
syntatic vs semantic links

### ISSUE THREAD

**Issue by arademaker** [own-pt/own-en-legacy#12]
```
w: a LINK b
```
this links sense of word a with sense of word b.

```
link: w
```
this links synset with synset (using the word `w` of the target as reference).

how to link a word to a synset? Some links in PWN are between sense-synset.

**Comment by fcbr** [comment]
can you give an example in WN 3.0 of a link between a word and a synset?

**Comment by arademaker** [comment]
http://arademaker.github.io/files/gwc-2016-icv.pdf

I am trying the query below with reasoniong turned on. still running


```
select ?a ?b {
  ?a a wn30:Synset .
  ?a ?c ?b .
  ?b a wn30:WordSense .
}
```

**Comment by arademaker** [comment]
note that the data file format (http://wordnet.princeton.edu/wordnet/man/wndb.5WN.html) can contains this kind of link. 

but the lexicographer files may not 

```
{ [ personhood, noun.Tops:person,+ ] identity,@ (being a person; "finding her own personhood as a campus activist") }
```

so maybe our modeling is wrong and the links are between sense-sense or synset-synset but not between sense-synset and synset-sense. if that is the case, our https://github.com/own-pt/openWordnet-PT/blob/master/wn30.ttl.

**Comment by arademaker** [comment]
ok, it seems that no synset-sense or sense-synset exists. 

```
egrep " 000[1-9] " data.* 
egrep " 0[1-9]00 " data.* 
```

We need to refine our `wn30.ttl` model.

**Comment by fcbr** [comment]
Looks like there is no issue here, then.
