### ISSUE TITLE
read.lisp should not use symbol names

### ISSUE THREAD

**Issue by fcbr** [own-pt/own-en-legacy#14]
This line is the problem:

https://github.com/own-pt/wordnet-dsl/blob/74593f13be30a395ed5f584537747849b1d66047/src/read.lisp#L7

While it work on Macs due to case insensitive file systems, it fails on Linux.  I recommend switching to strings instead of symbols for the filenames.

**Comment by hmuniz** [comment]
341b38d8771d970ceae409e2884055caceebbf50 changes that.

**Comment by arademaker** [comment]
Why not a hash of strings instead of symbols ? But this is a minor problem for now

**Comment by arademaker** [comment]
@fcbr the proposed change solves the issues ?

**Comment by fcbr** [comment]
Yep, closing it.
