### ISSUE TITLE
We should remove suffixes from labels

### ISSUE THREAD

**Issue by fcbr** [own-pt/own-en-legacy#16]
I just imported a partial conversion to RDF noticed that the labels of the words also contain the suffixes used to disambiguate the sense ids.  These suffixes should be removed from the labels.  Pay attention to "words" that are simply numbers!

Example:

```
<https://w3id.org/own-pt/wn30-en/instances/word-snappy4> 
      <https://w3id.org/own-pt/wn30/schema/lexicalForm> "snappy4" .
```

should be:

```
<https://w3id.org/own-pt/wn30-en/instances/word-snappy4> 
      <https://w3id.org/own-pt/wn30/schema/lexicalForm> "snappy" .
```

**Comment by arademaker** [comment]
is it really necessary to expose the `4` ? 

The word should be 

 ```
<https://w3id.org/own-pt/wn30-en/instances/word-snappy> 
      <https://w3id.org/own-pt/wn30/schema/lexicalForm> "snappy" .
```

don't you think?

**Comment by fcbr** [comment]
That means that we would share words between senses?  That may work...

**Comment by hmuniz** [comment]
I guess the e1a6511b3a0ae28fb4c821216259092cfd8ca179 and 07519963f769e2ba5010546fec081c7ed83cee72 removed suffixes from labels.

**Comment by arademaker** [comment]
@fcbr yes, words should have only one instance connected with more than one sense when they are polysemic. Related with #17 ? can we close this issue ?
