### ISSUE TITLE
Duplicated sense ids

### ISSUE THREAD

**Issue by fcbr** [own-pt/own-en-legacy#17]
Example:

```
<https://w3id.org/own-pt/wn30-en/instances/word-delineate> 
   <https://w3id.org/own-pt/wn30/schema/lexicalForm> "delineate" .
<https://w3id.org/own-pt/wn30-en/instances/word-delineate> 
   <https://w3id.org/own-pt/wn30/schema/lexicalForm> "delineate" .
<https://w3id.org/own-pt/wn30-en/instances/word-delineate> 
   <https://w3id.org/own-pt/wn30/schema/lexicalForm> "delineate" .
```
Sense ids are unique _per namespace_ (e.g. `adj.all`, `verb.contact`, etc.), so when generating a single unified view of all sense, we should make them disambiguous by maybe prefixing with the namespace.

- adj.all:delineate
- verb.communication:delineate
- verb.contact:delineate
- verb.creation:delineate
- verb.stative:delineate

**Comment by hmuniz** [comment]
ffa9390cb65a04cdbddd27d86679c604bad0ffb9 makes senses been uniques.

**Comment by arademaker** [comment]
@fcbr your examples are words not senses or synsets ! I suggest only one word instance per lexicalForm. A word instance can be connected to more than one senses.

**Comment by arademaker** [comment]
can we close this issue?

**Comment by hmuniz** [comment]
With 912bb659ecbbf8f0118621f4d7037fabd523cf22 we can close.
```
$ grep '<https://w3id.org/own-pt/wn30-en/instances/word-delineate> <https://w3id.org/own-
pt/wn30/schema/lexicalForm>' final.nt
<https://w3id.org/own-pt/wn30-en/instances/word-delineate> <https://w3id.org/own-pt/wn30/schema/lexicalForm> "delineate" .
```
