### ISSUE TITLE
Problem with a pointer symbol

### ISSUE THREAD

**Issue by hmuniz** [own-pt/own-en-legacy#18]
The pointer symbol `+` wasn't replaced by `drf`.
 
https://github.com/own-pt/wordnet-dsl/blob/07519963f769e2ba5010546fec081c7ed83cee72/dict/adv.all.txt#L8882

**Comment by arademaker** [comment]
@hmuniz o @fcbr entrou de férias, vc acha que consegue olhar o código dele e corrigir?!

**Comment by arademaker** [comment]
Curiosamente, só achei este caso 

`$ grep + * | grep -v "g:"`

vou corrigir o arquivo não mão.

**Comment by arademaker** [comment]
The bug is in the data:

```
$ grep feasibly *
data.adv:00428572 02 r 02 practicably 0 feasibly 0 003 \ 01822563 a 0201 \ 01822563 a 0103 + 01822563 a 0201 | in a practicable manner; so as to be feasible
index.adv:feasibly r 1 2 \ + 1 0 00428572
index.sense:feasibly%4:02:00:: 00428572 1 0

$ egrep ^01822563 *
data.adj:01822563 00 s 05 feasible 0 executable 0 practicable 0 viable 0 workable 0 012 & 01821266 a 0000 + 02436963 v 0501 + 02525447 v 0501 + 01629589 v 0502 + 01668603 v 0501 + 00634906 v 0506 + 05151576 n 0401 + 05152150 n 0302 + 05203207 n 0201 + 05152364 n 0102 + 05152364 n 0101 + 00428572 r 0102 | capable of being done with means at hand and circumstances as they are
```

In the data.adv, note the link `+ 01822563 a 0201`. But there is not `+` link for adverbs in the documentation:

http://wordnet.princeton.edu/wordnet/man/wninput.5WN.html

We will consider this a duplicated link and remove it. Since we have already the `\ 01822563 a 0201`link.
